/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorSelectAsientos;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author TOSHIBA
 */
public class SeleccionarAsientosFrm extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form NewJFrame
     */
    public SeleccionarAsientosFrm() {
        this.setContentPane(fondo);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        primeraClase1 = new javax.swing.JButton();
        primeraClase2 = new javax.swing.JButton();
        primeraClase3 = new javax.swing.JButton();
        primeraClase4 = new javax.swing.JButton();
        claseEjecutiva1 = new javax.swing.JButton();
        claseEjecutiva3 = new javax.swing.JButton();
        claseEjecutiva2 = new javax.swing.JButton();
        claseTurista2 = new javax.swing.JButton();
        claseTurista3 = new javax.swing.JButton();
        claseTurista1 = new javax.swing.JButton();
        claseTurista4 = new javax.swing.JButton();
        claseTurista5 = new javax.swing.JButton();
        claseTurista6 = new javax.swing.JButton();
        claseTurista7 = new javax.swing.JButton();
        claseTurista8 = new javax.swing.JButton();
        claseTurista11 = new javax.swing.JButton();
        claseTurista10 = new javax.swing.JButton();
        claseTurista12 = new javax.swing.JButton();
        claseTurista9 = new javax.swing.JButton();
        claseTurista14 = new javax.swing.JButton();
        claseTurista15 = new javax.swing.JButton();
        claseTurista13 = new javax.swing.JButton();
        claseTurista16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Asiento"));

        primeraClase1.setBackground(new java.awt.Color(7, 41, 78));
        primeraClase1.setForeground(new java.awt.Color(7, 41, 78));
        primeraClase1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        primeraClase1.setBorder(null);
        primeraClase1.setBorderPainted(false);
        primeraClase1.setContentAreaFilled(false);
        primeraClase1.setFocusPainted(false);
        primeraClase1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        primeraClase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraClase1ActionPerformed(evt);
            }
        });

        primeraClase2.setBackground(new java.awt.Color(7, 41, 78));
        primeraClase2.setForeground(new java.awt.Color(7, 41, 78));
        primeraClase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        primeraClase2.setBorder(null);
        primeraClase2.setBorderPainted(false);
        primeraClase2.setContentAreaFilled(false);
        primeraClase2.setFocusPainted(false);
        primeraClase2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        primeraClase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraClase2ActionPerformed(evt);
            }
        });

        primeraClase3.setBackground(new java.awt.Color(7, 41, 78));
        primeraClase3.setForeground(new java.awt.Color(7, 41, 78));
        primeraClase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        primeraClase3.setBorder(null);
        primeraClase3.setBorderPainted(false);
        primeraClase3.setContentAreaFilled(false);
        primeraClase3.setFocusPainted(false);
        primeraClase3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        primeraClase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraClase3ActionPerformed(evt);
            }
        });

        primeraClase4.setBackground(new java.awt.Color(7, 41, 78));
        primeraClase4.setForeground(new java.awt.Color(7, 41, 78));
        primeraClase4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        primeraClase4.setBorder(null);
        primeraClase4.setBorderPainted(false);
        primeraClase4.setContentAreaFilled(false);
        primeraClase4.setFocusPainted(false);
        primeraClase4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        primeraClase4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraClase4ActionPerformed(evt);
            }
        });

        claseEjecutiva1.setBackground(new java.awt.Color(7, 41, 78));
        claseEjecutiva1.setForeground(new java.awt.Color(7, 41, 78));
        claseEjecutiva1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseEjecutiva1.setBorder(null);
        claseEjecutiva1.setBorderPainted(false);
        claseEjecutiva1.setContentAreaFilled(false);
        claseEjecutiva1.setFocusPainted(false);
        claseEjecutiva1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseEjecutiva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseEjecutiva1ActionPerformed(evt);
            }
        });

        claseEjecutiva3.setBackground(new java.awt.Color(7, 41, 78));
        claseEjecutiva3.setForeground(new java.awt.Color(7, 41, 78));
        claseEjecutiva3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseEjecutiva3.setBorder(null);
        claseEjecutiva3.setBorderPainted(false);
        claseEjecutiva3.setContentAreaFilled(false);
        claseEjecutiva3.setFocusPainted(false);
        claseEjecutiva3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseEjecutiva3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseEjecutiva3ActionPerformed(evt);
            }
        });

        claseEjecutiva2.setBackground(new java.awt.Color(7, 41, 78));
        claseEjecutiva2.setForeground(new java.awt.Color(7, 41, 78));
        claseEjecutiva2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseEjecutiva2.setBorder(null);
        claseEjecutiva2.setBorderPainted(false);
        claseEjecutiva2.setContentAreaFilled(false);
        claseEjecutiva2.setFocusPainted(false);
        claseEjecutiva2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseEjecutiva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseEjecutiva2ActionPerformed(evt);
            }
        });

        claseTurista2.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista2.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista2.setBorder(null);
        claseTurista2.setBorderPainted(false);
        claseTurista2.setContentAreaFilled(false);
        claseTurista2.setFocusPainted(false);
        claseTurista2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista2ActionPerformed(evt);
            }
        });

        claseTurista3.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista3.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista3.setBorder(null);
        claseTurista3.setBorderPainted(false);
        claseTurista3.setContentAreaFilled(false);
        claseTurista3.setFocusPainted(false);
        claseTurista3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista3ActionPerformed(evt);
            }
        });

        claseTurista1.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista1.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista1.setBorder(null);
        claseTurista1.setBorderPainted(false);
        claseTurista1.setContentAreaFilled(false);
        claseTurista1.setFocusPainted(false);
        claseTurista1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista1ActionPerformed(evt);
            }
        });

        claseTurista4.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista4.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista4.setBorder(null);
        claseTurista4.setBorderPainted(false);
        claseTurista4.setContentAreaFilled(false);
        claseTurista4.setFocusPainted(false);
        claseTurista4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista4ActionPerformed(evt);
            }
        });

        claseTurista5.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista5.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista5.setBorder(null);
        claseTurista5.setBorderPainted(false);
        claseTurista5.setContentAreaFilled(false);
        claseTurista5.setFocusPainted(false);
        claseTurista5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista5ActionPerformed(evt);
            }
        });

        claseTurista6.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista6.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista6.setBorder(null);
        claseTurista6.setBorderPainted(false);
        claseTurista6.setContentAreaFilled(false);
        claseTurista6.setFocusPainted(false);
        claseTurista6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista6ActionPerformed(evt);
            }
        });

        claseTurista7.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista7.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista7.setBorder(null);
        claseTurista7.setBorderPainted(false);
        claseTurista7.setContentAreaFilled(false);
        claseTurista7.setFocusPainted(false);
        claseTurista7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista7ActionPerformed(evt);
            }
        });

        claseTurista8.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista8.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista8.setBorder(null);
        claseTurista8.setBorderPainted(false);
        claseTurista8.setContentAreaFilled(false);
        claseTurista8.setFocusPainted(false);
        claseTurista8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista8ActionPerformed(evt);
            }
        });

        claseTurista11.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista11.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista11.setBorder(null);
        claseTurista11.setBorderPainted(false);
        claseTurista11.setContentAreaFilled(false);
        claseTurista11.setFocusPainted(false);
        claseTurista11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista11ActionPerformed(evt);
            }
        });

        claseTurista10.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista10.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista10.setBorder(null);
        claseTurista10.setBorderPainted(false);
        claseTurista10.setContentAreaFilled(false);
        claseTurista10.setFocusPainted(false);
        claseTurista10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista10ActionPerformed(evt);
            }
        });

        claseTurista12.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista12.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista12.setBorder(null);
        claseTurista12.setBorderPainted(false);
        claseTurista12.setContentAreaFilled(false);
        claseTurista12.setFocusPainted(false);
        claseTurista12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista12ActionPerformed(evt);
            }
        });

        claseTurista9.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista9.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista9.setBorder(null);
        claseTurista9.setBorderPainted(false);
        claseTurista9.setContentAreaFilled(false);
        claseTurista9.setFocusPainted(false);
        claseTurista9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista9ActionPerformed(evt);
            }
        });

        claseTurista14.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista14.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista14.setBorder(null);
        claseTurista14.setBorderPainted(false);
        claseTurista14.setContentAreaFilled(false);
        claseTurista14.setFocusPainted(false);
        claseTurista14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista14ActionPerformed(evt);
            }
        });

        claseTurista15.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista15.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista15.setBorder(null);
        claseTurista15.setBorderPainted(false);
        claseTurista15.setContentAreaFilled(false);
        claseTurista15.setFocusPainted(false);
        claseTurista15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista15ActionPerformed(evt);
            }
        });

        claseTurista13.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista13.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista13.setBorder(null);
        claseTurista13.setBorderPainted(false);
        claseTurista13.setContentAreaFilled(false);
        claseTurista13.setFocusPainted(false);
        claseTurista13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista13ActionPerformed(evt);
            }
        });

        claseTurista16.setBackground(new java.awt.Color(7, 41, 78));
        claseTurista16.setForeground(new java.awt.Color(7, 41, 78));
        claseTurista16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoRecortado.png"))); // NOI18N
        claseTurista16.setBorder(null);
        claseTurista16.setBorderPainted(false);
        claseTurista16.setContentAreaFilled(false);
        claseTurista16.setFocusPainted(false);
        claseTurista16.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAsientoOcupado.png"))); // NOI18N
        claseTurista16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTurista16ActionPerformed(evt);
            }
        });

        jLabel1.setText("A");

        btnReservar.setText("Reservar");
        btnReservar.setBorder(null);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        jLabel2.setText("B");

        jLabel3.setText("C");

        jLabel4.setText("D");

        jLabel5.setText("E");

        jLabel6.setText("F");

        jLabel7.setText("G");

        jLabel8.setText("1");

        jLabel9.setText("2");

        jLabel10.setText("1");

        jLabel11.setText("2");

        jLabel12.setText("1");

        jLabel13.setText("2");

        jLabel14.setText("3");

        jLabel15.setText("1");

        jLabel16.setText("2");

        jLabel17.setText("3");

        jLabel18.setText("4");

        jLabel19.setText("1");

        jLabel20.setText("2");

        jLabel21.setText("3");

        jLabel22.setText("4");

        jLabel23.setText("1");

        jLabel24.setText("2");

        jLabel25.setText("3");

        jLabel26.setText("4");

        jLabel27.setText("1");

        jLabel28.setText("2");

        jLabel29.setText("3");

        jLabel30.setText("4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel8)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1)
                        .addGap(182, 182, 182)
                        .addComponent(primeraClase1)
                        .addGap(35, 35, 35)
                        .addComponent(primeraClase2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(jLabel10)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel2)
                        .addGap(183, 183, 183)
                        .addComponent(primeraClase3)
                        .addGap(35, 35, 35)
                        .addComponent(primeraClase4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel12)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel13)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel3)
                        .addGap(152, 152, 152)
                        .addComponent(claseEjecutiva1)
                        .addGap(15, 15, 15)
                        .addComponent(claseEjecutiva2)
                        .addGap(15, 15, 15)
                        .addComponent(claseEjecutiva3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel15)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel16)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel17)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel4)
                        .addGap(112, 112, 112)
                        .addComponent(claseTurista8)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista1)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista2)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel19)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel20)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel21)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel5)
                        .addGap(103, 103, 103)
                        .addComponent(claseTurista4)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista5)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista6)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel23)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel24)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel25)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel6)
                        .addGap(103, 103, 103)
                        .addComponent(claseTurista9)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista10)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista11)
                        .addGap(15, 15, 15)
                        .addComponent(claseTurista12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel27)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel28)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel29)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel30)))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel7)
                .addGap(102, 102, 102)
                .addComponent(claseTurista13)
                .addGap(15, 15, 15)
                .addComponent(claseTurista14)
                .addGap(15, 15, 15)
                .addComponent(claseTurista15)
                .addGap(15, 15, 15)
                .addComponent(claseTurista16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReservar)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addComponent(primeraClase1)
                    .addComponent(primeraClase2))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addComponent(primeraClase3)
                    .addComponent(primeraClase4))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addComponent(claseEjecutiva1)
                    .addComponent(claseEjecutiva2)
                    .addComponent(claseEjecutiva3))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addComponent(claseTurista8)
                    .addComponent(claseTurista1)
                    .addComponent(claseTurista2)
                    .addComponent(claseTurista3))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addComponent(claseTurista4)
                    .addComponent(claseTurista5)
                    .addComponent(claseTurista6)
                    .addComponent(claseTurista7))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addComponent(claseTurista9)
                    .addComponent(claseTurista10)
                    .addComponent(claseTurista11)
                    .addComponent(claseTurista12))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7))
                            .addComponent(claseTurista13)
                            .addComponent(claseTurista14)
                            .addComponent(claseTurista15)
                            .addComponent(claseTurista16))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReservar)
                        .addGap(54, 54, 54))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        Menu vMenu = new Menu();
        vMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReservarActionPerformed

    private void claseTurista16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista16ActionPerformed

    private void claseTurista13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista13ActionPerformed

    private void claseTurista15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista15ActionPerformed

    private void claseTurista14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista14ActionPerformed

    private void claseTurista9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista9ActionPerformed

    private void claseTurista12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista12ActionPerformed

    private void claseTurista10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista10ActionPerformed

    private void claseTurista11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista11ActionPerformed

    private void claseTurista8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista8ActionPerformed

    private void claseTurista7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista7ActionPerformed

    private void claseTurista6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista6ActionPerformed

    private void claseTurista5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista5ActionPerformed

    private void claseTurista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista4ActionPerformed

    private void claseTurista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista1ActionPerformed

    private void claseTurista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista3ActionPerformed

    private void claseTurista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTurista2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseTurista2ActionPerformed

    private void claseEjecutiva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseEjecutiva2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseEjecutiva2ActionPerformed

    private void claseEjecutiva3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseEjecutiva3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseEjecutiva3ActionPerformed

    private void claseEjecutiva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseEjecutiva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseEjecutiva1ActionPerformed

    private void primeraClase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraClase4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeraClase4ActionPerformed

    private void primeraClase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraClase3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeraClase3ActionPerformed

    private void primeraClase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraClase2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeraClase2ActionPerformed

    private void primeraClase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraClase1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeraClase1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SeleccionarAsientosFrm v = new SeleccionarAsientosFrm();
        ControladorSelectAsientos csa = new ControladorSelectAsientos(v);
        v.setVisible(true);
        v.setLocationRelativeTo(v);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnReservar;
    public javax.swing.JButton claseEjecutiva1;
    public javax.swing.JButton claseEjecutiva2;
    public javax.swing.JButton claseEjecutiva3;
    public javax.swing.JButton claseTurista1;
    public javax.swing.JButton claseTurista10;
    public javax.swing.JButton claseTurista11;
    public javax.swing.JButton claseTurista12;
    public javax.swing.JButton claseTurista13;
    public javax.swing.JButton claseTurista14;
    public javax.swing.JButton claseTurista15;
    public javax.swing.JButton claseTurista16;
    public javax.swing.JButton claseTurista2;
    public javax.swing.JButton claseTurista3;
    public javax.swing.JButton claseTurista4;
    public javax.swing.JButton claseTurista5;
    public javax.swing.JButton claseTurista6;
    public javax.swing.JButton claseTurista7;
    public javax.swing.JButton claseTurista8;
    public javax.swing.JButton claseTurista9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton primeraClase1;
    public javax.swing.JButton primeraClase2;
    public javax.swing.JButton primeraClase3;
    public javax.swing.JButton primeraClase4;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            
            imagen = new ImageIcon(getClass().getResource("/imagenes/avion3.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
